spring:
  application:
    name: auth-user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_user_db
    username: auth_user
    password: auth_user_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  port: 8081

auth-user-service:
  security:
    password:
      bcrypt-strength: 10
